export const CONTINUE_WATCHING_REQUEST = "CONTINUE_WATCHING_REQUEST";
export const CONTINUE_WATCHING_SUCCESS = "CONTINUE_WATCHING_SUCCESS";
export const CONTINUE_WATCHING_FAIL = "CONTINUE_WATCHING_FAIL";

export const WATCH_DELETE_ONE_REQUEST = "WATCH_DELETE_ONE_REQUEST";
export const WATCH_DELETE_ONE_SUCCESS = "WATCH_DELETE_ONE_SUCCESS";
export const WATCH_DELETE_ONE_FAIL = "WATCH_DELETE_ONE_FAIL";
export const WATCH_DELETE_ONE_RESET = "WATCH_DELETE_ONE_RESET";

export const WATCH_CLEAR_ALL_REQUEST = "WATCH_CLEAR_ALL_REQUEST";
export const WATCH_CLEAR_ALL_SUCCESS = "WATCH_CLEAR_ALL_SUCCESS";
export const WATCH_CLEAR_ALL_FAIL = "WATCH_CLEAR_ALL_FAIL";
export const WATCH_CLEAR_ALL_RESET = "WATCH_CLEAR_ALL_RESET";