export const CONTINUE_WATCHING_REQUEST = "CONTINUE_WATCHING_REQUEST";
export const CONTINUE_WATCHING_SUCCESS = "CONTINUE_WATCHING_SUCCESS";
export const CONTINUE_WATCHING_FAIL = "CONTINUE_WATCHING_FAIL";
